### ISSUE TITLE
Undefined constant Symfony\Component\Console\Command\Command::SUCCESS

### ISSUE THREAD

**Issue by jissereitsma** [yireo/magento2-replace-tools#12]
Example of warning error:
```bash
app@0897ff71b97a:~/magento2$ composer replace:list
+---------+---------+
| Package | Version |
+---------+---------+
PHP Fatal error:  Uncaught Error: Undefined constant Symfony\Component\Console\Command\Command::SUCCESS in /data/web/magento2/vendor/yireo/magento2-replace-tools/src/Composer/Command/ReplaceListCommand.php:32
Stack trace:
#0 phar:///usr/local/bin/composer22/vendor/symfony/console/Command/Command.php(245): Yireo\ReplaceTools\Composer\Command\ReplaceListCommand->execute()
#1 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#2 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#3 phar:///usr/local/bin/composer22/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#4 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#5 phar:///usr/local/bin/composer22/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#6 phar:///usr/local/bin/composer22/bin/composer(83): Composer\Console\Application->run()
#7 /usr/local/bin/composer22(29): require('...')
#8 {main}
  thrown in /data/web/magento2/vendor/yireo/magento2-replace-tools/src/Composer/Command/ReplaceListCommand.php on line 32

Fatal error: Uncaught Error: Undefined constant Symfony\Component\Console\Command\Command::SUCCESS in /data/web/magento2/vendor/yireo/magento2-replace-tools/src/Composer/Command/ReplaceListCommand.php:32
Stack trace:
#0 phar:///usr/local/bin/composer22/vendor/symfony/console/Command/Command.php(245): Yireo\ReplaceTools\Composer\Command\ReplaceListCommand->execute()
#1 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#2 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#3 phar:///usr/local/bin/composer22/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#4 phar:///usr/local/bin/composer22/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#5 phar:///usr/local/bin/composer22/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#6 phar:///usr/local/bin/composer22/bin/composer(83): Composer\Console\Application->run()
#7 /usr/local/bin/composer22(29): require('...')
#8 {main}
  thrown in /data/web/magento2/vendor/yireo/magento2-replace-tools/src/Composer/Command/ReplaceListCommand.php on line 32
```

See https://github.com/yireo/magento2-replace-tools/issues/9

**Comment by jissereitsma** [comment]
Please try upgrading `composer` to the latest version first.
